### ISSUE TITLE
포지션 수정을 범용적으로 적용할 수 있는 함수를 구현합니다.

### ISSUE THREAD

**Issue by swimmiee** [evmos-stayking-house/defi-contract#26]
# 추가/개선 필요 요소
`addDebt`, `addEquity`, `repayDebt` 등의 함수를 포괄할 수 있는 `editPosition` 함수를 구현합니다.

# 추가/개선 필요 이유
포지션 수정을 위한 액션(담보 추가, 추가 대출 등)이 복합적으로 동시에 이루어질 수 있기 때문에,
그 액션들을 한 번에 수행할 수 있는 함수를 구현합니다.

**Comment by swimmiee** [comment]
event name과의 통일성을 위해 함수명을 `editPosition` -> `changePosition`으로 변경합니다.

**Comment by swimmiee** [comment]
```Solidity
function changePosition (
  address debtToken,
  int changeEquityInBase,
  int changeDebtInBase,
  uint repayDebtInBase
)
```

함수 호출 시 `changeEquityInBase`, `changeDebtInBase`, `repayDebtInBase` 의 값에 따라 아래 5가지 케이스로 나뉠 수 있습니다.
1. changeEquityInBase > 0 
  - 자기 자본을 투입해서 Position Value 증가시킴 (call _stake function)
  - debt ratio 감소
2. changeEquityInBase < 0 
  - 포지션 내 일부 자기자본을 뺌으로써 Position value를 감소시킴 (call _unstake function)
  - debt ratio 증가
3. changeDebtInBase > 0
  - 빚을 더 내서 Position Value를 높임 (call _stake function)
  - debt ratio 증가
4. changeEquityInBase < 0 (repay debt by unstaking)
  - 포지션 내 일부 debt를 뺌으로써 Position Value를 감소시킴 (call _unstake function)
  - debt ratio 감소
5. repayDebtInBase < 0 (repay debt with own EVMOS)
  - 포지션 변화 없이 자기 자본으로 빚을 갚음 (not call _stake/_unstake function)
  - debt ratio 감소

**Comment by gloryan0829** [comment]
오홍.. 컨트랙에서 자료형을 unsigned integer 만 써봤는데  integer 는 처음 써보네영
